version: '3.8'

services:
    server:
        container_name: trackster-api
        restart: always
        build: ./
        ports:
            - '8080:8080'
        env_file:
            - ./.env
        restart: on-failure
        # depends_on:
        #     db:
        #         condition: service_healthy

    db:
        container_name: postgres-trackster-api
        build: ./build/postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=trackster
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
        ports:
            - '5432:5432'
        # healthcheck:
        #     test: ['CMD-SHELL', 'pg_isready -U postgres']
        #     interval: 10s
        #     timeout: 5s
        #     retries: 5
