version: '3.8'

services:
    trackster-api:
        container_name: trackster-api
        restart: always
        build: ./
        ports:
            - '8080:8080'
        environment:
            - TRACKSTER_API_PORT=8080
            - ACCESS_TOKEN_SECRET=secret
            - DATABASE_URL=postgres://postgres:password@localhost:5432/trackster?sslmode=disable
        # depends_on:
        #     postgres:
        #         condition: service_healthy
    postgres:
        container_name: postgres_trackster_api
        build: ./build/postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=trackster
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
        ports:
            - '5432:5432'
        # healthcheck:
        #     test: ['CMD-SHELL', 'pg_isready -U postgres']
        #     interval: 10s
        #     timeout: 5s
        #     retries: 5
