version: '3.8'

services:
    trackster-api:
        container_name: trackster-api
        build: ./
        ports:
            - '8080:8080'
        environment:
            - TRACKSTER_API_PORT=8080
            - ACCESS_TOKEN_SECRET=secret
